apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloud-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloud-app-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20 #wait before downcalling
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15 #evaluates the load